### ISSUE TITLE
add a `Mentioned in Awesome` button

### ISSUE THREAD

**Issue by LucasLarson** [LucasLarson/gunstage#102]
add the “Mentioned in Awesome” button as seen at [marwanhawari/stew@`2f6a9dd`&#160;§&#8239;stew](https://github.com/marwanhawari/stew/tree/2f6a9dd12f9a2d56b187a8e25be0ba39d4468943#stew):

---
live:
[![Mentioned in Awesome](https://github.com/sindresorhus/awesome/raw/a90737eb91368b3be912d1759f9573203ef9e70d/media/mentioned-badge.svg)](/unixorn/awesome-zsh-plugins)
```markdown
[![Mentioned in Awesome](https://github.com/sindresorhus/awesome/raw/a90737eb91368b3be912d1759f9573203ef9e70d/media/mentioned-badge.svg)](/unixorn/awesome-zsh-plugins)
```

---
or archivable / for posterity:
[![Mentioned in Awesome](https://web.archive.org/web/20220305135317id_/github.com/sindresorhus/awesome/raw/a90737eb91368b3be912d1759f9573203ef9e70d/media/mentioned-badge.svg)](https://web.archive.org/web/20220305180324/https://github.com/unixorn/awesome-zsh-plugins/commit/b47bbcdea53c8bc65ca28641b7751977eba500a8)
```markdown
[![Mentioned in Awesome](https://web.archive.org/web/20220305135317id_/github.com/sindresorhus/awesome/raw/a90737eb91368b3be912d1759f9573203ef9e70d/media/mentioned-badge.svg)](https://web.archive.org/web/20220305180324/https://github.com/unixorn/awesome-zsh-plugins/commit/b47bbcdea53c8bc65ca28641b7751977eba500a8)
```

**Comment by RishiKumarRay** [comment]
@LucasLarson <a href="https://github.com/avelino/awesome-go">
    <img src="https://awesome.re/mentioned-badge.svg" alt="Mentioned in Awesome Go"/>
  </a> 
is this what you want?

**Comment by RishiKumarRay** [comment]
unable to get this button after pasting the code

**Comment by LucasLarson** [comment]
Hey thanks!

> unable to get this button after pasting the code

I think it’s because the readme is an AsciiDoc file, but my snippet https://github.com/LucasLarson/gunstage/issues/102#issue-1160480257 is Markdown.

You probably want something like
```asciidoc
link:https://github.com/unixorn/awesome-zsh-plugins[image:https://github.com/sindresorhus/awesome/raw/a90737eb91368b3be912d1759f9573203ef9e70d/media/mentioned-badge.svg[🕶
Mentioned in Awesome,title="🕶 Mentioned in Awesome"]]
```

**Comment by RishiKumarRay** [comment]
@LucasLarson please review
