### ISSUE TITLE
Please add a top-level license file

### ISSUE THREAD

**Issue by unixorn** [LucasLarson/gunstage#28]
**Describe the bug**

The license is only in the `gunstage` script, so it doesn't get automatically found and displayed by github on the main repository page

**To Reproduce**

N/A

**Expected behavior**
If there's a separate LICENSE file, github will parse it and display your license in the main page of the repository

**Desktop (please complete the following information):**
- Browser:  All

**Comment by LucasLarson** [comment]
Hi @unixorn,

This repo’s license is a top-level file, albeit with a lowercase name ([license.adoc](https://github.com/LucasLarson/gunstage/blob/main/license.adoc)). The license has 100% bidirectionally with the GNU GPL v3.

I’ll add a license section to the readme unless you think these two links are sufficient:
[![license](https://user-images.githubusercontent.com/91468/98451723-9489fb80-2116-11eb-8798-5bf0692e0f2f.png)]()

**Comment by unixorn** [comment]
It may just be that GH's automation doesn't recognize .adoc files

**Comment by LucasLarson** [comment]
Yes, the GitHub parser’s support of AsciiDoc is... uneven.

Please close the issue if it’s no longer actionable? And thank you.
